export enum AppRoutes {
  Home = '/',
  About = '/about',
  Contact = '/contact',
  Blog = '/blog',
  SignIn = '/auth/sign-in',
  SignUp = '/auth/sign-up',
  ForgotPassword = '/auth/forgot/password',
  AdminManageDashboard = '/admin/dashboard',
  AdminManageContests = '/admin/manage-contests',
  AdminManageInstructors = '/admin/manage-instructors',
  AdminManageStudents = '/admin/manage-students',
  AdminManageMessages = '/admin/manage-messages',
  AdminManageNotifications = '/admin/manage-notifications',
  AdminManageQuestions = '/admin/manage-questions',
  AdminManageSettings = '/admin/manage-settings',
}
