export const users = [
  {
    password: '12345678',
    key: 999999,
    email: 'admin@yahoo.com',
    agreement: true,
    role: 'ADMIN',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'أحمد',
      personalImage: '/icons/user-avatar.svg',
      lastName: 'عمر',
      dateOfBirth: '1975-10-07T11:43:24.616Z',
      country: 'مصر',
    },
  },
  {
    password: '12345678',
    key: 1,
    email: 'y1@yahoo.com',
    agreement: true,
    role: 'TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'أحمد',
      personalImage: '/icons/user-avatar.svg',
      lastName: 'عمر',
      dateOfBirth: '1975-10-07T11:43:24.616Z',
      country: 'مصر',
    },
  },
  {
    password: '12345678',
    key: 2,
    email: 'y2@yahoo.com',
    agreement: true,
    role: 'TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'جمال',
      personalImage: '/icons/user-avatar.svg',
      lastName: 'مصطفى',
      dateOfBirth: '1982-10-07T11:43:24.616Z',
      country: 'مصر',
    },
  },
  {
    password: '12345678',
    key: 3,
    email: 'y3@yahoo.com',
    agreement: true,
    role: 'TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'جمال',
      personalImage: '/icons/user-avatar.svg',
      lastName: 'مديوني',
      dateOfBirth: '1981-10-07T11:43:24.616Z',
      country: 'مصر',
    },
  },
  {
    password: '12345678',
    key: 4,
    email: 'y4@yahoo.com',
    agreement: true,
    role: 'TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'جمال',
      personalImage: '/icons/user-avatar.svg',
      lastName: 'الفاروق',
      dateOfBirth: '1981-10-07T11:43:24.616Z',
      country: 'الجزائر',
    },
  },
  {
    password: '12345678',
    key: 5,
    email: 'y5@yahoo.com',
    agreement: true,
    role: 'TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'عمر',
      personalImage: '/icons/user-avatar.svg',
      lastName: 'الفاروق',
      dateOfBirth: '1981-10-07T11:43:24.616Z',
      country: 'العراق',
    },
  },
  {
    password: '12345678',
    key: 6,
    email: 'y6@yahoo.com',
    agreement: true,
    role: 'TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'كمال',
      personalImage: '/icons/user-avatar.svg',
      lastName: 'عبد الباقي',
      dateOfBirth: '1985-10-07T11:43:24.616Z',
      country: 'مصر',
    },
  },
  {
    password: '12345678',
    key: 7,
    email: 'y7@yahoo.com',
    agreement: true,
    role: 'TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'محمد',
      personalImage: '/icons/user-avatar.svg',
      lastName: 'فيصل',
      dateOfBirth: '1985-10-07T11:43:24.616Z',
      country: 'مصر',
    },
  },
  {
    password: '12345678',
    key: 8,
    email: 'y8@yahoo.com',
    agreement: true,
    role: 'TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'محمد',
      personalImage: '/icons/user-avatar.svg',
      lastName: 'مصطفى',
      dateOfBirth: '1985-10-07T11:43:24.616Z',
      country: 'مصر',
    },
  },
  {
    password: '12345678',
    key: 9,
    email: 'y9@yahoo.com',
    agreement: true,
    role: 'TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'تركي',
      personalImage: '/icons/user-avatar.svg',
      lastName: 'محمود',
      dateOfBirth: '1980-10-07T11:43:24.616Z',
      country: 'مصر',
    },
  },
  {
    password: '12345678',
    key: 10,
    email: 'y10@yahoo.com',
    agreement: true,
    role: 'TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'عبد الحميد',
      personalImage: '/icons/user-avatar.svg',
      lastName: 'المنشاوي',
      dateOfBirth: '1980-10-07T11:43:24.616Z',
      country: 'الأردن',
    },
  },
  {
    password: '12345678',
    key: 11,
    email: 'y11@yahoo.com',
    agreement: true,
    role: 'TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'وهيبة',
      personalImage: '/icons/user-avatar.svg',
      lastName: 'مصطفى',
      dateOfBirth: '1980-10-07T11:43:24.616Z',
      country: 'مصر',
    },
  },
  {
    password: '12345678',
    key: 12,
    email: 'y12@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'هيبه',
      lastName: 'مصطفى',
      country: 'مصر',
      level: 'Fifteen',
      dateOfBirth: '2012-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 13,
    email: 'y13@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'هيبه',
      country: 'مصر',
      level: 'Fifteen',
      dateOfBirth: '2012-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 14,
    email: 'y14@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماجد',
      lastName: 'مصطفى',
      country: 'مصر',
      level: 'Fifteen',
      dateOfBirth: '2012-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 15,
    email: 'y15@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'ماجد',
      country: 'مصر',
      level: 'Fifteen',
      dateOfBirth: '2012-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 16,
    email: 'y16@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'مروان',
      country: 'مصر',
      level: 'Fifteen',
      dateOfBirth: '2012-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 17,
    email: 'y17@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'مروان',
      lastName: 'مصطفى',
      country: 'مصر',
      level: 'Fifteen',
      dateOfBirth: '2012-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 18,
    email: 'y18@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'مالك',
      lastName: 'مصطفى',
      country: 'مصر',
      level: 'Fifteen',
      dateOfBirth: '2010-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 19,
    email: 'y19@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'مالك',
      country: 'مصر',
      level: 'Fifteen',
      dateOfBirth: '2010-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 20,
    email: 'y20@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'مدحت',
      lastName: 'مصطفى',
      country: 'مصر',
      level: 'Sixteen',
      dateOfBirth: '2010-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 21,
    email: 'y21@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'مدحت',
      country: 'مصر',
      level: 'Sixteen',
      dateOfBirth: '2010-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 22,
    email: 'y22@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'مسعد',
      lastName: 'مصطفى',
      country: 'مصر',
      level: 'Sixteen',
      dateOfBirth: '2009-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 23,
    email: 'y23@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'مسعد',
      country: 'الكويت',
      level: 'Sixteen',
      dateOfBirth: '2009-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 24,
    email: 'y24@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'معتز',
      country: 'الكويت',
      level: 'Sixteen',
      dateOfBirth: '2009-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 25,
    email: 'y25@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'معتز',
      lastName: 'مصطفى',
      country: 'الكويت',
      level: 'Sixteen',
      dateOfBirth: '2009-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 26,
    email: 'y26@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'راكان',
      country: 'الكويت',
      level: 'Sixteen',
      dateOfBirth: '2009-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 27,
    email: 'y27@yahoo.com',
    agreement: true,
    role: 'STUDENT',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'راكان',
      lastName: 'مصطفى',
      country: 'الكويت',
      level: 'Sixteen',
      dateOfBirth: '2009-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 28,
    email: 'y28@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'جعفر',
      lastName: 'مصطفى',
      country: 'الكويت',
      level: 'Sixteen',
      dateOfBirth: '2009-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 29,
    email: 'y29@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'جعفر',
      country: 'الكويت',
      level: 'Eighteen',
      dateOfBirth: '2009-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 30,
    email: 'y30@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'زبير',
      country: 'الكويت',
      level: 'Eighteen',
      dateOfBirth: '2009-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 31,
    email: 'y31@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'زبير',
      lastName: 'مصطفى',
      country: 'مصر',
      level: 'Seventeen',
      dateOfBirth: '2008-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 32,
    email: 'y32@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'رضوان',
      country: 'مصر',
      level: 'Seventeen',
      dateOfBirth: '2008-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 33,
    email: 'y33@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'رضوان',
      lastName: 'مصطفى',
      country: 'العراق',
      level: 'Seventeen',
      dateOfBirth: '2008-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 34,
    email: 'y34@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'حسين',
      lastName: 'مصطفى',
      country: 'العراق',
      level: 'Seventeen',
      dateOfBirth: '2008-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 35,
    email: 'y35@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'حسين',
      lastName: 'بلال',
      country: 'العراق',
      level: 'Seventeen',
      dateOfBirth: '2008-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 36,
    email: 'y36@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'حكيم',
      country: 'العراق',
      level: 'Eighteen',
      dateOfBirth: '2008-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 37,
    email: 'y37@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'حسين',
      lastName: 'حكيم',
      country: 'مصر',
      level: 'Eighteen',
      dateOfBirth: '2008-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 38,
    email: 'y38@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'أجود',
      lastName: 'مصطفى',
      country: 'الجزائر',
      level: 'Eighteen',
      dateOfBirth: '2008-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 39,
    email: 'y39@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'أحنف',
      country: 'الجزائر',
      level: 'Eighteen',
      dateOfBirth: '2008-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 40,
    email: 'y40@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'ماهر',
      lastName: 'أدهم',
      country: 'الجزائر',
      level: 'Eighteen',
      dateOfBirth: '2008-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
  {
    password: '12345678',
    key: 41,
    email: 'y41@yahoo.com',
    agreement: true,
    role: 'STUDENT_TEACHER',
    emailConfirmed: true,
    isActive: true,
    profile: {
      firstName: 'أيوب',
      lastName: 'مصطفى',
      country: 'الجزائر',
      level: 'Eighteen',
      dateOfBirth: '2007-10-07T11:43:24.616Z',
      personalImage: '/icons/user-avatar.svg',
      birthCertImage: '/icons/empty-doc.svg',
      letterImage: '/icons/empty-doc.svg',
    },
  },
];
