version: '3.8'

services:
  authdb:
    image: percona
    restart: unless-stopped
    volumes:
      - auth-data:/var/lib/mysql
    # Uncomment to change startup options
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
      MYSQL_DATABASE: olympiad
    networks:
      - auth_network

  contestdb:
    image: percona
    restart: unless-stopped
    volumes:
      - cts-data:/var/lib/mysql
    # Uncomment to change startup options
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
      MYSQL_DATABASE: olympiad
    networks:
      - cts_network

  minio:
    image: bitnami/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio-root-user
      MINIO_ROOT_PASSWORD: minio-root-password
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - web_network

  contest:
    image: docker.io/amineyagoub/olympiad-contest
    hostname: contest
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://user:pass123@contestdb:3306/olympiad
      - WAIT_HOSTS= contestdb:3306
    networks:
      - cts_network
    depends_on:
      contestdb:
        condition: service_healthy

  auth:
    image: docker.io/amineyagoub/olympiad-auth
    hostname: auth
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://user:pass123@authdb:3306/olympiad
      - WAIT_HOSTS= authdb:3306
    networks:
      - auth_network
    depends_on:
      authdb:
        condition: service_healthy

  api:
    image: docker.io/amineyagoub/olympiad-gateway
    restart: unless-stopped
    environment:
      - GATEWAY_CONTEST_SERVICE_HOST=http://contest:3001/graphql
      - GATEWAY_AUTH_SERVICE_HOST=http://auth:3003/graphql
      - GATEWAY_CORS_ORIGIN=http://185.250.36.113
    networks:
      - auth_network
      - cts_network
      - web_network
    depends_on:
      contest:
        condition: service_healthy
    ports:
      - 3005

  wss:
    image: docker.io/amineyagoub/olympiad-wss
    restart: unless-stopped
    networks:
      - web_network
    ports:
      - 3002

volumes:
  auth-data: null
  cts-data: null
  minio_data: null

networks:
  auth_network:
  cts_network:
  web_network:
