name: Build Containers for Prod & Push to Dockerhub
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev

env:
  AUTH_TEST_TAG: amineyagoub/olympiad-auth:test
  AUTH_LATEST_TAG: amineyagoub/olympiad-auth:latest

jobs:
  build-and-deploy-auth:
    name: Build and Deploy auth
    runs-on: ubuntu-latest
    services:
      percona:
        image: percona
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: pass123
          MYSQL_DATABASE: olympiad
        ports:
          - 3306:3306
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/auth/Dockerfile
          load: true
          tags: ${{ env.AUTH_TEST_TAG }}

      - name: Test auth container
        run: |
          docker run -itd --network=${{ job.services.percona.network }} \
              -e DATABASE_URL=mysql://user:pass123@percona:3306/olympiad \
              -e WAIT_HOSTS=percona:3306 \
              --rm ${{ env.AUTH_TEST_TAG }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/auth/Dockerfile
          push: true
          tags: ${{ env.AUTH_LATEST_TAG }}
