name: Build Containers for Prod & Push to Dockerhub
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev

jobs:
  build-and-deploy-contest:
    name: Build and Deploy contest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          file: apps/contest/Dockerfile
          cache-from: type=registry,ref=amineyagoub/olympiad-contest:latest
          cache-to: type=inline
          tags: amineyagoub/olympiad-contest:latest

  build-and-deploy-gateway:
    name: Build and Deploy gateway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          file: apps/gateway/Dockerfile
          cache-from: type=registry,ref=amineyagoub/olympiad-gateway:latest
          cache-to: type=inline
          tags: amineyagoub/olympiad-gateway:latest

  build-and-deploy-wss:
    name: Build and Deploy wss
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          file: apps/wss/Dockerfile
          cache-from: type=registry,ref=amineyagoub/olympiad-wss:latest
          cache-to: type=inline
          tags: amineyagoub/olympiad-wss:latest

  build-and-deploy-frontend:
    name: Build and Deploy frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          file: apps/frontend/Dockerfile
          cache-from: type=registry,ref=amineyagoub/olympiad-frontend:latest
          cache-to: type=inline
          tags: amineyagoub/olympiad-frontend:latest
